builds:
  - # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux
      - darwin
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - arm
      - arm64

brews:
  - tap:
      owner: fhopfensperger
      name: homebrew-tap
    folder: Formula
    homepage: https://fhopfensperger.github.io
    description: Transforms json log into human readable output
    license: Apache 2.0
    test: |
      system "#{bin}/json-log-to-human-readable -v"
    dependencies:
      - name: go
        type: optional
      - name: git
        type: optional
    install: |-
      bin.install "json-log-to-human-readable"
